steps:
  release:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME##docker-}"
      tags: "${CI_COMMIT_TAG##v}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    group: build
  release-node_20:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      build_args: "NODE_MAJOR=20"
      platforms: linux/amd64,linux/arm64
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME##docker-}"
      tags: "${CI_COMMIT_TAG##v}-node_20"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    group: build
when:
  - event: tag
    ref: refs/tags/v*
